### ISSUE TITLE
Basic repository setup

### ISSUE THREAD

**Issue by Vyvy-vi** [FitDevs-withKat/discord-bot#1]
The repository needs some initialisation files that can allow contributors to have a neat contribution flow:
- [ ] README.md (describing the project, along with some information like - How to set up bot locally, invite bot to your server etc.)
- [ ] CONTRIBUTING.md (a file explaining the contribution process - How to open issues, how to claim an issue, how to keep their fork up to date, commit message guidelines, etc.)
- [ ] CODE_OF_CONDUCT.md (a file laying down the rules and enforcement policies for the project)
- [ ] LICENSE (an open source license that protects contributors, users and maintainers)
- [ ] Issue Templates 
- [ ] PR Template

**Comment by joshuaHallee** [comment]
I made [this pull request](https://github.com/FitDevs-withKat/discord-bot/pull/2) that handles the following:

* Updated README
* Small blurb on how to handle adding a contribution
* Added CODE_OF_CONDUCT
* Added initial project setup if the [pull request](https://github.com/FitDevs-withKat/discord-bot/pull/3) of a very basic bot was approved
