### ISSUE TITLE
Create Bottom Ten Command

### ISSUE THREAD

**Issue by joshuaHallee** [FitDevs-withKat/discord-bot#16]
Currently we have a `/topten` command, it would be fun to have `/bottomten` command.

Copy the `topten.js` file and rename to `bottomten.js`. Modify the mongoose query to display ten users with the lowest total minutes.

**Comment by kemps-medeiros** [comment]
Hi @joshuaHallee , Can I try to do this task?

**Comment by kemps-medeiros** [comment]
Hi @joshuaHallee 
I've created PR https://github.com/FitDevs-withKat/discord-bot/pull/19 to solve this issue.

Please let me know if you need to make any changes or if you have any questions.

**Comment by joshuaHallee** [comment]
Thanks @kemps-medeiros for the contribution! The PR was merged into main branch 😄
