### ISSUE TITLE
Fix If Statement

### ISSUE THREAD

**Issue by joshuaHallee** [FitDevs-withKat/discord-bot#9]
Line 53, `index.js`

`if(!interaction.type === interaction.ApplicationCommand) return;`

should be

`if(interaction.type !== interaction.ApplicationCommand) return;`

This helps with code / logic readability.

**Comment by Vinitvh** [comment]
Hi, I would like to fix this.

**Comment by joshuaHallee** [comment]
PR #12 was merged - closing issue.
